name: Auto Push

on:
  schedule:
    - cron: '0 */* * 2 *'  # ทุก 6 ชั่วโมง

jobs:
  auto-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Run auto push script
      run: python auto_push.py
